### ISSUE TITLE
[Question] about `appx/web-view.min.js`

### ISSUE THREAD

**Issue by ce-manalang** [jcchikikomori/gcash-miniprogram-webview-sample#7]
Hi @jcchikikomori

Great work on this! Hope it's ok to ask a question though,

Where can I download the content of the JS file reference in this line: https://github.com/jcchikikomori/gcash-miniprogram-webview-sample/blob/da09517c281234ba338d0de3490818e917cfe855/views/index.html#L86

Thank you so much :)

**Comment by jcchikikomori** [comment]
> Where can I download the content of the JS file reference in this line:

Hello. This is a local file that only exists in Mini Program engine
https://miniprogram.gcash.com/docs/miniprogram_gcash/mpdev/component_open_web-view
